version: '3.7'
services:
  nestify-mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_ROOT_USER
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_ROOT_PASSWORD
    ports:
      - 27017:27017
    volumes:
      - mongodata:/data/db
      - mongodumps:/data/dumps
    networks:
      - nestifynet
  nestify-base-app:
    build:
      context: ./
      target: dev
    image: nestify-dev
    env_file:
      - ./dev.env
    networks:
      - nestifynet
    ports:
      - 3000:3000
    volumes:
      - schemas:/usr/src/app/jsonschemas
      - assets:/usr/src/app/assets

networks:
  nestifynet:

volumes:
  mongodata:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: $DOCKER_MONGODATA_DIR
  mongodumps:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: $DOCKER_MONGODUMPS_DIR
  schemas:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: $DOCKER_SCHEMAS_DIR
  assets:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: $DOCKER_ASSETS_DIR
