name: build
on:
  push:
    branches: [main, dev]
  workflow_dispatch: ~

jobs:
  dockerhub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: get branch
        run: |
          # https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-environment-variable
          TAG=${GITHUB_REF##*/}
          if [ "$TAG" == "master" ] ; then TAG=latest ; fi
          echo "TAG=$TAG" >> $GITHUB_ENV
      - name: docker build
        run: docker build -t nondef/nestify-base-app:$TAG --label "buildUrl=$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID" .
      - uses: docker/login-action@v1
        with:
          username: nondef
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: docker push
        run: docker push nondef/nestify-base-app:$TAG